[tool.poetry]
name = "ml-simple-notify"
version = "0.2.1"
description = "一个简单可扩展的消息通知库"
authors = ["miclon <jcnd@163.com>"]
readme = "README.md"
packages = [
    { include = 'notify', from = 'src' }
]

[tool.poetry.dependencies]
python = "^3.8"
usepy = "^0.1.34"
httpx = "^0.23.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
